version: '3'
services:
  clear:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clear
    ports:
      - "6277:6633"
    volumes:
      - ./data:/app/data
    environment:
      - JWT_SECRET="Welcome to Clear!"